### ISSUE TITLE
Failed installation

### ISSUE THREAD

**Issue by HeyLifeHD** [gao-lab/CPC2_standalone#3]
Dear CPC2 authors,

I have been trying to install and run CPC2. Therefore I have been installing biophython via conda and further cloned your github repository. However, installation seems to be incomplete. 

`
#create biopython conda environment to run cpc2
conda create --name biophython
conda activate biophython
conda install -c conda-forge biopython
pip install modules
#install cpc
cd tools/
git clone https://github.com/gao-lab/CPC2_standalone
cd CPC2_standalone
export CPC_HOME="$PWD"
cd libs/libsvm
gzip -dc libsvm-3.18.tar.gz | tar xf -
cd libsvm-3.18
make clean && make

#run prediction
cd $CPC_HOME
bin/CPC2.py -i (input_seq) -o (result_in_table)
`

Resulting in following error message:

`
Traceback (most recent call last):
  File "/home/heyj/tools/CPC2_standalone/bin/CPC2.py", line 8, in <module>
    import commands
ModuleNotFoundError: No module named 'commands'
`

Thanks for your support.

Best,

Joschka

**Comment by kkkyj** [comment]
Hi, Joschka

'commands' is a default module in python 2. If you are using python 3, please try this version https://github.com/gao-lab/CPC2_standalone/releases/tag/v1.0.1
