### ISSUE TITLE
create a conda package?

### ISSUE THREAD

**Issue by mthang** [gao-lab/CPC2_standalone#5]
Hi there,
I can see there is a CPC2 with python2 conda package on https://anaconda.org/cbp44/cpc2 . I wonder is there a plan to make the CPC2 python3 version on the conda repo?

Many thanks,
Mike

**Comment by gao-ge** [comment]
Dear Mike,

Thanks for your interest in the CPC package.

As you may notice already,  the conda package at https://anaconda.org/cbp44/cpc2 is not released/maintained by us.

We're actively working on building official pip/conda packages, please keep watching the repo news page!
