### ISSUE TITLE
Error about No excutable svm-predict on CPC2 path!

### ISSUE THREAD

**Issue by YIGUIz** [gao-lab/CPC2_standalone#7]
Hi, I run CPC2 by image, and Here is some errors. 
the commend:
`singularity exec /public/home/b20223040336/Workspace/long_read_rna/02code/singularity_images/cpc2_1.0.1--hdfd78af_0  CPC2.py -i ../final_transcriptome1.fa -o pro_ncrnas_cpc2_results`

The error file:
![image](https://github.com/user-attachments/assets/b3032de1-6889-4b1b-b329-1811dd11981a)

the output files:
![image](https://github.com/user-attachments/assets/b64b00b2-7712-44fe-a4bb-c49e4ede0bab)

**Comment by Ziwei-Liu** [comment]
Hey, I've met a same error, how did you fix this?
